// # Dosya Yolu: C:/Projects/TelefonRehberi/src/main/java/com/turkuazlabs/telefonrehberi/config/UiConfig.java
// # Amac: Swing ve FlatLaf arayuz sabitlerini merkezi olarak tanimlar.
// # Config - Java
// # Version: 2.41.0
// # Aciklama: Tema v3 ile kontrol radius, buton olculeri, focus halkasi ve kompakt chip geometrisini merkezi hale getirir.
// # Bagimli Oldugu Katman: Config
package com.turkuazlabs.telefonrehberi.config;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Set;

public final class UiConfig {
    public static final int WINDOW_WIDTH = 1600;
    public static final int WINDOW_HEIGHT = 960;
    public static final int WINDOW_MIN_WIDTH = 1040;
    public static final int WINDOW_MIN_HEIGHT = 700;
    public static final Dimension WINDOW_SIZE = new Dimension(WINDOW_WIDTH, WINDOW_HEIGHT);
    public static final Dimension WINDOW_MIN_SIZE = new Dimension(WINDOW_MIN_WIDTH, WINDOW_MIN_HEIGHT);

    public static final int SIDEBAR_WIDTH = 238;
    public static final int UI_GAP = 18;
    public static final int UI_SMALL_GAP = 12;
    public static final int UI_PADDING = 26;
    public static final int FORM_COLUMNS = 24;
    public static final int SEARCH_COLUMNS = 34;
    public static final int CONTACT_LIST_ROW_HEIGHT = 80;
    public static final int CONTACT_LIST_ROW_HEIGHT_COMPACT = 64;
    public static final int CONTACT_BROWSER_MIN_WIDTH = 300;
    public static final int CONTACT_WORKSPACE_MIN_WIDTH = 360;
    public static final int CONTACT_BROWSER_DEFAULT_WIDTH = 360;
    public static final int CONTACT_BROWSER_MAX_WIDTH = 440;
    public static final int CONTACT_SPLIT_DIVIDER_SIZE = 8;
    public static final double CONTACT_BROWSER_WEIGHT = 0.32;
    public static final int CONTACT_ACTION_COMPACT_BREAKPOINT = 560;
    public static final int BULK_ACTION_WIDE_COLUMNS = 2;
    public static final int BULK_ACTION_COMPACT_COLUMNS = 1;
    public static final int BULK_ACTION_COMPACT_BREAKPOINT = 560;
    public static final int BULK_PREVIEW_NAME_LIMIT = 4;
    public static final int FILTER_PANEL_GAP = 7;
    public static final int FILTER_CONTROL_HEIGHT = 32;
    public static final int FILTER_CHIP_HEIGHT = 30;
    public static final int FILTER_CHIP_GAP = 5;
    public static final int FILTER_CHIP_WIDE_COLUMNS = 2;
    public static final int FILTER_CHIP_COMPACT_COLUMNS = 1;
    public static final int FILTER_CHIP_COMPACT_BREAKPOINT = 280;
    public static final int FILTER_DRAWER_MAX_HEIGHT = 158;
    public static final int QUICK_ACTION_COMPACT_BREAKPOINT = 640;
    public static final int QUICK_ACTION_WIDE_COLUMNS = 4;
    public static final int QUICK_ACTION_COMPACT_COLUMNS = 2;
    public static final int FORM_ACTION_WIDE_COLUMNS = 3;
    public static final int FORM_ACTION_COMPACT_COLUMNS = 2;
    public static final int EDITOR_FORM_WIDE_COLUMNS = 2;
    public static final int EDITOR_FORM_COMPACT_COLUMNS = 1;
    public static final int EDITOR_FORM_COMPACT_BREAKPOINT = 620;
    public static final int EDITOR_FORM_GAP = 12;
    public static final int EDITOR_FIELD_LABEL_GAP = 6;
    public static final int EDITOR_FORM_MIN_HEIGHT = 120;
    public static final int EDITOR_AREA_HEIGHT = 112;
    public static final int EDITOR_NOTES_HEIGHT = 150;
    public static final int EDITOR_TAB_HEIGHT = 38;
    public static final float EDITOR_FIELD_LABEL_SIZE = 12f;
    public static final float EDITOR_SECTION_TITLE_SIZE = 14f;
    public static final float EDITOR_SECTION_SUBTITLE_SIZE = 12f;
    public static final int WORKSPACE_GAP = 16;
    public static final int HEADER_TITLE_FONT_DELTA = 8;
    public static final int HEADER_SUBTITLE_FONT_DELTA = -1;
    public static final int STATUS_BORDER_TOP = 0;
    public static final int UNDO_NOTICE_TIMEOUT_MS = 12000;
    public static final int UNDO_NOTICE_ARC = 12;
    public static final int UNDO_NOTICE_GAP = 10;
    public static final int UNDO_NOTICE_PADDING_X = 14;
    public static final int UNDO_NOTICE_PADDING_Y = 5;
    public static final int TEXT_AREA_ROWS = 5;
    public static final int TEXT_AREA_COLUMNS = 26;
    public static final int AVATAR_SIZE = 84;
    public static final int PROFILE_AVATAR_SIZE = 104;
    public static final int PROFILE_AVATAR_COMPACT_SIZE = 78;
    public static final int PROFILE_COMPACT_BREAKPOINT = 620;
    public static final float PROFILE_NAME_FONT_SIZE = 23f;
    public static final float PROFILE_NAME_COMPACT_FONT_SIZE = 19.5f;
    public static final float PROFILE_COMPANY_FONT_SIZE = 14f;
    public static final float PROFILE_COMPANY_COMPACT_FONT_SIZE = 12.5f;
    public static final int PROFILE_INFO_WIDE_COLUMNS = 2;
    public static final int PROFILE_INFO_COMPACT_COLUMNS = 1;
    public static final int PROFILE_INFO_COMPACT_BREAKPOINT = 620;
    public static final int PROFILE_INFO_GAP = 12;
    public static final int PROFILE_FIELD_LABEL_GAP = 5;
    public static final int PROFILE_INFO_MIN_HEIGHT = 88;
    public static final float PROFILE_FIELD_LABEL_SIZE = 11.5f;
    public static final float PROFILE_FIELD_VALUE_SIZE = 13.5f;
    public static final int ACTIVITY_FILTER_GAP = 6;
    public static final int ACTIVITY_ROW_GAP = 8;
    public static final int ACTIVITY_ROW_PADDING_Y = 8;
    public static final int ACTIVITY_ROW_MIN_HEIGHT = 54;
    public static final int ACTIVITY_RAIL_WIDTH = 22;
    public static final int ACTIVITY_DOT_SIZE = 9;
    public static final int ACTIVITY_DOT_TOP = 7;
    public static final int ACTIVITY_LINE_WIDTH = 1;
    public static final int ACTIVITY_TEXT_GAP = 3;
    public static final float ACTIVITY_ACTION_FONT_SIZE = 13f;
    public static final float ACTIVITY_DESCRIPTION_FONT_SIZE = 11.5f;
    public static final float ACTIVITY_DATE_FONT_SIZE = 10.5f;
    public static final int CONTACT_LIST_AVATAR_SIZE = 42;
    public static final int CONTACT_LIST_CELL_ARC = 14;
    public static final int CONTACT_LIST_CELL_MARGIN = 3;
    public static final int CONTACT_LIST_CELL_PADDING_X = 10;
    public static final int CONTACT_LIST_CELL_PADDING_Y = 8;
    public static final int CONTACT_LIST_CELL_GAP = 11;
    public static final int CONTACT_LIST_TEXT_GAP = 3;
    public static final int CONTACT_LIST_SELECTED_BAR_WIDTH = 3;
    public static final int CONTACT_LIST_SELECTED_BAR_INSET = 10;
    public static final int CONTACT_LIST_NAME_MAX_CHARS = 26;
    public static final int CONTACT_LIST_DETAIL_MAX_CHARS = 28;
    public static final int CONTACT_LIST_META_MAX_CHARS = 30;
    public static final float CONTACT_LIST_NAME_FONT_SIZE = 14.5f;
    public static final float CONTACT_LIST_DETAIL_FONT_SIZE = 12.5f;
    public static final float CONTACT_LIST_META_FONT_SIZE = 11f;
    public static final float CONTACT_LIST_FAVORITE_FONT_SIZE = 15f;
    public static final int STAT_CARD_MIN_WIDTH = 156;
    public static final int DASHBOARD_STATS_WIDE_COLUMNS = 6;
    public static final int DASHBOARD_STATS_MEDIUM_COLUMNS = 3;
    public static final int DASHBOARD_STATS_COMPACT_COLUMNS = 2;
    public static final int DASHBOARD_STATS_MEDIUM_BREAKPOINT = 1120;
    public static final int DASHBOARD_STATS_COMPACT_BREAKPOINT = 720;
    public static final int DASHBOARD_FEATURE_WIDE_COLUMNS = 2;
    public static final int DASHBOARD_FEATURE_MEDIUM_COLUMNS = 1;
    public static final int DASHBOARD_FEATURE_COMPACT_COLUMNS = 1;
    public static final int DASHBOARD_FEATURE_MEDIUM_BREAKPOINT = 940;
    public static final int DASHBOARD_FEATURE_COMPACT_BREAKPOINT = 620;
    public static final int DASHBOARD_GRID_GAP = 14;
    public static final int DASHBOARD_STAT_CARD_HEIGHT = 132;
    public static final int DASHBOARD_FEATURE_CARD_MIN_HEIGHT = 230;
    public static final int DASHBOARD_ACTION_WIDE_COLUMNS = 2;
    public static final int DASHBOARD_ACTION_COMPACT_COLUMNS = 1;
    public static final int DASHBOARD_ACTION_COMPACT_BREAKPOINT = 430;
    public static final int DASHBOARD_STATUS_ROW_HEIGHT = 56;
    public static final int DASHBOARD_ICON_BADGE_SIZE = 38;
    public static final int DASHBOARD_ICON_SIZE = 18;
    public static final int DASHBOARD_ICON_ARC = 14;
    public static final int DASHBOARD_SECTION_GAP = 18;
    public static final int DASHBOARD_CAPABILITY_WIDE_COLUMNS = 3;
    public static final int DASHBOARD_CAPABILITY_MEDIUM_COLUMNS = 1;
    public static final int DASHBOARD_CAPABILITY_COMPACT_COLUMNS = 1;
    public static final int DASHBOARD_CAPABILITY_MEDIUM_BREAKPOINT = 920;
    public static final int DASHBOARD_CAPABILITY_COMPACT_BREAKPOINT = 620;
    public static final int DASHBOARD_CAPABILITY_MIN_HEIGHT = 92;
    public static final int MANAGEMENT_GRID_WIDE_COLUMNS = 2;
    public static final int MANAGEMENT_GRID_COMPACT_COLUMNS = 1;
    public static final int MANAGEMENT_GRID_BREAKPOINT = 920;
    public static final int MANAGEMENT_GRID_GAP = 16;
    public static final int MANAGEMENT_LIST_CARD_HEIGHT = 470;
    public static final int MANAGEMENT_DETAIL_CARD_HEIGHT = 470;
    public static final int MANAGEMENT_LIST_ROW_HEIGHT = 78;
    public static final int MANAGEMENT_LIST_CELL_ARC = 14;
    public static final int MANAGEMENT_LIST_CELL_MARGIN = 3;
    public static final int MANAGEMENT_LIST_CELL_PADDING_X = 12;
    public static final int MANAGEMENT_LIST_CELL_PADDING_Y = 10;
    public static final int MANAGEMENT_SELECTED_BAR_WIDTH = 3;
    public static final int MANAGEMENT_SELECTED_BAR_INSET = 11;
    public static final int MANAGEMENT_COLOR_DOT_SIZE = 13;
    public static final float MANAGEMENT_ITEM_TITLE_SIZE = 14.5f;
    public static final float MANAGEMENT_ITEM_SUBTITLE_SIZE = 11.5f;
    public static final float MANAGEMENT_ITEM_BADGE_SIZE = 11.5f;
    public static final int MANAGEMENT_ACTION_WIDE_COLUMNS = 2;
    public static final int MANAGEMENT_ACTION_COMPACT_COLUMNS = 1;
    public static final int MANAGEMENT_ACTION_BREAKPOINT = 460;
    public static final int OPERATIONS_GRID_WIDE_COLUMNS = 2;
    public static final int OPERATIONS_GRID_COMPACT_COLUMNS = 1;
    public static final int OPERATIONS_GRID_BREAKPOINT = 920;
    public static final int OPERATIONS_CARD_HEIGHT = 470;
    public static final int OPERATIONS_CARD_MIN_HEIGHT = 340;
    public static final int OPERATIONS_LIST_ROW_HEIGHT = 78;
    public static final int TRANSFER_GRID_WIDE_COLUMNS = 3;
    public static final int TRANSFER_GRID_MEDIUM_COLUMNS = 2;
    public static final int TRANSFER_GRID_COMPACT_COLUMNS = 1;
    public static final int TRANSFER_GRID_MEDIUM_BREAKPOINT = 1180;
    public static final int TRANSFER_GRID_COMPACT_BREAKPOINT = 700;
    public static final int TRANSFER_GRID_GAP = 16;
    public static final int TRANSFER_CARD_HEIGHT = 265;
    public static final int TRANSFER_CARD_MIN_HEIGHT = 245;
    public static final int TRANSFER_INFO_CARD_HEIGHT = 92;
    public static final int SYNC_GRID_WIDE_COLUMNS = 3;
    public static final int SYNC_GRID_MEDIUM_COLUMNS = 2;
    public static final int SYNC_GRID_COMPACT_COLUMNS = 1;
    public static final int SYNC_GRID_MEDIUM_BREAKPOINT = 1050;
    public static final int SYNC_GRID_COMPACT_BREAKPOINT = 620;
    public static final int SYNC_STATUS_CARD_HEIGHT = 170;
    public static final int SYNC_INFO_CARD_HEIGHT = 150;
    public static final int BACKUP_GRID_WIDE_COLUMNS = 2;
    public static final int BACKUP_GRID_COMPACT_COLUMNS = 1;
    public static final int BACKUP_GRID_BREAKPOINT = 920;
    public static final int BACKUP_SUMMARY_CARD_HEIGHT = 260;
    public static final int BACKUP_HISTORY_CARD_HEIGHT = 420;
    public static final int SETTINGS_CARD_MIN_HEIGHT = 150;
    public static final int SETTINGS_DATA_CARD_MIN_HEIGHT = 190;
    public static final int SETTINGS_CONTENT_GAP = 14;
    public static final int DEFAULT_BACKUP_RETENTION = 5;
    public static final int MAX_BACKUP_RETENTION = 5;
    public static final int CARD_ARC = 16;
    public static final int CARD_PADDING = 20;
    public static final int NAV_HEIGHT = 42;
    public static final int NAV_CHILD_HEIGHT = 38;
    public static final int NAV_SECTION_HEIGHT = 34;
    public static final int NAV_CHILD_GAP = 2;
    public static final float NAV_SECTION_FONT_SIZE = 11.5f;
    public static final int NAV_ICON_SIZE = 19;
    public static final int CARD_SHADOW_SIZE = 4;
    public static final int CARD_SHADOW_OFFSET = 1;
    public static final int HEADER_TITLE_SIZE = 30;
    public static final int HEADER_SUBTITLE_SIZE = 15;
    public static final int PRIMARY_BUTTON_HEIGHT = 40;
    public static final int TEXT_BUTTON_HEIGHT = 36;
    public static final int BUTTON_MIN_WIDTH = 88;
    public static final int BUTTON_ARC = 10;
    public static final int BUTTON_FOCUS_RING_WIDTH = 2;
    public static final int CHIP_ARC = 999;
    public static final float BUTTON_FONT_SIZE = 13.5f;
    public static final float TEXT_BUTTON_FONT_SIZE = 13f;
    public static final float CHIP_FONT_SIZE = 12f;
    public static final int QUICK_ACTION_HEIGHT = 40;
    public static final int QUICK_ACTION_GAP = 8;
    public static final int QUICK_ACTION_ICON_SIZE = 18;
    public static final int SCROLL_UNIT_INCREMENT = 18;
    public static final int SCROLL_BLOCK_INCREMENT = 72;
    public static final String CONTACT_MODE_VIEW = "contact_view";
    public static final String CONTACT_MODE_EDIT = "contact_edit";
    public static final String CONTACT_MODE_BULK = "contact_bulk";
    public static final String STAT_INDICATOR = "\u25CF";

    public static final Color BRAND_PRIMARY = new Color(18, 140, 126);
    public static final Color BRAND_PRIMARY_DARK = new Color(11, 123, 111);
    public static final Color BRAND_DARK = new Color(24, 37, 43);
    public static final Color BRAND_DARKER = new Color(16, 23, 27);
    public static final Color BRAND_NAV_ACTIVE = new Color(8, 105, 96);
    public static final Color BRAND_SOFT = new Color(230, 245, 242);
    public static final Color BRAND_TEXT_SOFT = new Color(132, 149, 157);
    public static final Color STATUS_DARK = new Color(241, 247, 247);
    public static final Color DANGER = new Color(190, 45, 54);

    public static final String PAGE_DASHBOARD = "dashboard";
    public static final String PAGE_CONTACTS = "contacts";
    public static final String PAGE_GROUPS = "groups";
    public static final String PAGE_TAGS = "tags";
    public static final String PAGE_SMART_LISTS = "smart_lists";
    public static final String PAGE_HISTORY = "history";
    public static final String PAGE_MAINTENANCE = "maintenance";
    public static final String PAGE_IMPORT_EXPORT = "import_export";
    public static final String PAGE_TRASH = "trash";
    public static final String PAGE_SYNC = "sync";
    public static final String PAGE_BACKUP = "backup";
    public static final String PAGE_SETTINGS = "settings";
    public static final String PAGE_ABOUT = "about";
    private static final Set<String> KNOWN_PAGES = Set.of(
            PAGE_DASHBOARD, PAGE_CONTACTS, PAGE_GROUPS, PAGE_TAGS, PAGE_SMART_LISTS, PAGE_HISTORY,
            PAGE_MAINTENANCE, PAGE_IMPORT_EXPORT, PAGE_TRASH, PAGE_SYNC, PAGE_BACKUP, PAGE_SETTINGS, PAGE_ABOUT
    );

    public static final String FLATLAF_LIGHT_CLASS = "com.formdev.flatlaf.FlatLightLaf";
    public static final String FLATLAF_DARK_CLASS = "com.formdev.flatlaf.FlatDarkLaf";

    public static final String CLIENT_PLACEHOLDER_TEXT = "JTextField.placeholderText";
    public static final String CLIENT_SHOW_CLEAR_BUTTON = "JTextField.showClearButton";
    public static final String CLIENT_ROUND_RECT = "JComponent.roundRect";
    public static final String CLIENT_BUTTON_TYPE = "JButton.buttonType";
    public static final String CLIENT_STYLE = "FlatLaf.style";
    public static final String CLIENT_TABBED_TAB_TYPE = "JTabbedPane.tabType";
    public static final String CLIENT_TABBED_SHOW_TAB_SEPARATORS = "JTabbedPane.showTabSeparators";
    public static final String CLIENT_TABBED_TAB_HEIGHT = "JTabbedPane.tabHeight";
    public static final String TABBED_TAB_TYPE_CARD = "card";
    public static final String BUTTON_TYPE_ROUND_RECT = "roundRect";

    public static final String ACTION_FOCUS_SEARCH = "focus-search";
    public static final String ACTION_CLEAR_FORM = "clear-form";
    public static final String ACTION_REFRESH = "refresh";
    public static final String ACTION_UNDO_BULK = "undo-bulk";
    public static final String ACTION_REDO_BULK = "redo-bulk";

    public static boolean isKnownPage(String page) {
        return page != null && KNOWN_PAGES.contains(page);
    }

    private UiConfig() {
    }
}
